# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory
WORKDIR /usr/src/app

# Copy source code to the working directory
COPY . .

# Command to run your code
CMD ["python", "code.py"]
